#!/usr/bin/env python3
"""Map a written PATO top-surface temperature field back to the SU2 wall profile.

Inputs
------
1. PATO Ta field after a material-response step.
2. The PATO spatial face CSV generated by map_su2_profile_to_pato_faces.py.
3. The topology-ordered SU2 wall profile generated by
   extract_su2_wall_profile.py.

The PATO values are face-centered. They are interpreted as samples at the
face-center arclengths and linearly interpolated onto the topology-ordered
SU2 wall vertices. Endpoint values use constant extrapolation from the nearest
PATO face center.

This tool intentionally does NOT assume that VTK point IDs equal PySU2 marker
vertex IDs. It preserves x/y/z and wall arclength for a later coordinate-based
PySU2 application step.
"""

from __future__ import annotations

import argparse
import bisect
import csv
import hashlib
import json
import re
from pathlib import Path


def matching_brace(s: str, open_i: int) -> int:
    depth = 0
    in_line = False
    in_block = False
    in_string = False
    quote = ""
    i = open_i

    while i < len(s):
        c = s[i]
        n = s[i + 1] if i + 1 < len(s) else ""

        if in_line:
            if c == "\n":
                in_line = False
            i += 1
            continue

        if in_block:
            if c == "*" and n == "/":
                in_block = False
                i += 2
            else:
                i += 1
            continue

        if in_string:
            if c == "\\":
                i += 2
                continue
            if c == quote:
                in_string = False
            i += 1
            continue

        if c == "/" and n == "/":
            in_line = True
            i += 2
            continue

        if c == "/" and n == "*":
            in_block = True
            i += 2
            continue

        if c in ("'", '"'):
            in_string = True
            quote = c
            i += 1
            continue

        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return i

        i += 1

    raise RuntimeError("unbalanced braces")


def read_top_temperature_values(path: Path) -> list[float]:
    text = path.read_text()

    m = re.search(r"\bboundaryField\b\s*\{", text)
    if not m:
        raise RuntimeError("boundaryField not found in PATO Ta")

    bf_open = text.find("{", m.start())
    bf_close = matching_brace(text, bf_open)
    bf = text[bf_open + 1 : bf_close]

    pm = re.search(r"(?m)^[ \t]*top[ \t]*\s*\{", bf)
    if not pm:
        raise RuntimeError("top patch not found in PATO Ta")

    po = bf.find("{", pm.start())
    pc = matching_brace(bf, po)
    top = bf[pm.start() : pc + 1]

    nm = re.search(
        r"\bvalue\s+nonuniform\s+List<scalar>\s+(\d+)\s*\((.*?)\)\s*;",
        top,
        flags=re.S,
    )
    if not nm:
        raise RuntimeError(
            "top/value is not a nonuniform List<scalar>; "
            "a written spatial PATO temperature field is required"
        )

    declared = int(nm.group(1))
    vals = [float(x) for x in nm.group(2).split()]

    if len(vals) != declared:
        raise RuntimeError(
            f"PATO top value count mismatch: declared={declared}, parsed={len(vals)}"
        )

    return vals


def linear_sample(x: list[float], y: list[float], q: float) -> float:
    if q <= x[0]:
        return y[0]
    if q >= x[-1]:
        return y[-1]

    j = bisect.bisect_right(x, q) - 1
    x0, x1 = x[j], x[j + 1]
    y0, y1 = y[j], y[j + 1]

    if x1 == x0:
        return 0.5 * (y0 + y1)

    a = (q - x0) / (x1 - x0)
    return y0 + a * (y1 - y0)


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("pato_ta", type=Path)
    ap.add_argument("pato_face_csv", type=Path)
    ap.add_argument("su2_wall_profile_csv", type=Path)
    ap.add_argument("output_csv", type=Path)
    ap.add_argument("--metadata", type=Path)
    ap.add_argument(
        "--status",
        choices=("TEST_ONLY", "CONVERGED_SOURCE"),
        default="TEST_ONLY",
    )
    args = ap.parse_args()

    t_face = read_top_temperature_values(args.pato_ta)

    with args.pato_face_csv.open(newline="") as f:
        face_rows = list(csv.DictReader(f))

    if len(face_rows) != len(t_face):
        raise SystemExit(
            f"ERROR: PATO face rows={len(face_rows)} but temperature values={len(t_face)}"
        )

    s_face = [float(r["s_center"]) for r in face_rows]

    if any(b <= a for a, b in zip(s_face, s_face[1:])):
        raise SystemExit("ERROR: PATO face-center arclength is not strictly increasing")

    with args.su2_wall_profile_csv.open(newline="") as f:
        wall_rows = list(csv.DictReader(f))

    if len(wall_rows) < 2:
        raise SystemExit("ERROR: SU2 wall profile requires at least two vertices")

    s_wall = [float(r["s"]) for r in wall_rows]

    if any(b <= a for a, b in zip(s_wall, s_wall[1:])):
        raise SystemExit("ERROR: SU2 wall arclength is not strictly increasing")

    if abs(s_wall[-1] - float(face_rows[-1]["s1"])) > 1e-9:
        raise SystemExit(
            "ERROR: PATO and SU2 wall arclengths differ: "
            f"SU2={s_wall[-1]:.16e}, PATO={float(face_rows[-1]['s1']):.16e}"
        )

    t_wall = [linear_sample(s_face, t_face, s) for s in s_wall]

    args.output_csv.parent.mkdir(parents=True, exist_ok=True)

    fields = [
        "path_index",
        "point_id",
        "s",
        "s_normalized",
        "x",
        "y",
        "z",
        "wall_temperature_K",
    ]

    with args.output_csv.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()

        for row, temp in zip(wall_rows, t_wall):
            w.writerow(
                {
                    "path_index": row["path_index"],
                    "point_id": row["point_id"],
                    "s": row["s"],
                    "s_normalized": row["s_normalized"],
                    "x": row["x"],
                    "y": row["y"],
                    "z": row["z"],
                    "wall_temperature_K": f"{temp:.12e}",
                }
            )

    metadata_path = args.metadata or args.output_csv.with_suffix(
        args.output_csv.suffix + ".json"
    )

    meta = {
        "status": args.status,
        "physical_interpretation_allowed": args.status != "TEST_ONLY",
        "pato_ta": str(args.pato_ta.resolve()),
        "pato_face_csv": str(args.pato_face_csv.resolve()),
        "su2_wall_profile_csv": str(args.su2_wall_profile_csv.resolve()),
        "pato_face_count": len(t_face),
        "su2_wall_vertex_count": len(t_wall),
        "wall_arclength_m": s_wall[-1],
        "pato_temperature_min_K": min(t_face),
        "pato_temperature_max_K": max(t_face),
        "su2_mapped_temperature_min_K": min(t_wall),
        "su2_mapped_temperature_max_K": max(t_wall),
        "endpoint_policy": "constant extrapolation from nearest PATO face center",
        "interior_policy": "linear interpolation in common wall arclength",
        "driver_vertex_mapping_policy": (
            "Do not use VTK point_id as PySU2 iVertex. "
            "Match PySU2 marker coordinates to this profile during application."
        ),
        "sha256": {
            "pato_ta": sha256(args.pato_ta),
            "pato_face_csv": sha256(args.pato_face_csv),
            "su2_wall_profile_csv": sha256(args.su2_wall_profile_csv),
            "output_csv": sha256(args.output_csv),
        },
    }

    metadata_path.write_text(json.dumps(meta, indent=2) + "\n")

    print(f"OUTPUT_CSV={args.output_csv}")
    print(f"METADATA={metadata_path}")
    print(f"PATO_FACE_COUNT={len(t_face)}")
    print(f"SU2_WALL_VERTEX_COUNT={len(t_wall)}")
    print(f"WALL_ARCLENGTH={s_wall[-1]:.12e}")
    print(f"PATO_T_MIN={min(t_face):.12e}")
    print(f"PATO_T_MAX={max(t_face):.12e}")
    print(f"SU2_T_MIN={min(t_wall):.12e}")
    print(f"SU2_T_MAX={max(t_wall):.12e}")
    print(f"SU2_T_FIRST={t_wall[0]:.12e}")
    print(f"SU2_T_LAST={t_wall[-1]:.12e}")
    print("PATO_TO_SU2_TEMPERATURE_MAP=PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
