#!/usr/bin/env python3
"""Create a PATO basicWallHeatFluxTemperature patch snippet from SU2 wall CSV.

This is the first one-way coupling level. It deliberately uses the direct
PATO heat-flux BC rather than converting SU2 q_w into B-prime quantities.

The generated snippet does not edit a PATO case automatically.

Sign handling:
  same              PATO q = SU2 Heat_Flux
  flip              PATO q = -SU2 Heat_Flux
  positive-magnitude PATO q = abs(SU2 Heat_Flux)

For the initial thermal-response test, positive-magnitude is useful because
the PATO implementation applies refGrad = q/kappa and positive q is treated
as an imposed heating-gradient magnitude. Full sign-preserving spatial
coupling should be verified against the chosen material-mesh orientation.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path


def read_rows(path: Path):
    with path.open(newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise SystemExit("ERROR: empty interface CSV")
    return rows


def choose(rows, selection: str, point_id: int | None):
    q = [float(r["Heat_Flux"]) for r in rows]

    if selection == "max-abs":
        i = max(range(len(rows)), key=lambda j: abs(q[j]))
    elif selection == "max":
        i = max(range(len(rows)), key=lambda j: q[j])
    elif selection == "min":
        i = min(range(len(rows)), key=lambda j: q[j])
    elif selection == "mean":
        return None, sum(q) / len(q)
    elif selection == "point":
        if point_id is None:
            raise SystemExit("ERROR: --point-id is required for --selection point")
        matches = [i for i, r in enumerate(rows) if int(r["point_id"]) == point_id]
        if len(matches) != 1:
            raise SystemExit(f"ERROR: point_id {point_id} not found uniquely")
        i = matches[0]
    else:
        raise AssertionError(selection)

    return i, q[i]


def apply_sign(q: float, mode: str) -> float:
    if mode == "same":
        return q
    if mode == "flip":
        return -q
    if mode == "positive-magnitude":
        return abs(q)
    raise AssertionError(mode)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("csv", type=Path)
    ap.add_argument("snippet", type=Path)
    ap.add_argument(
        "--selection",
        choices=("max-abs", "max", "min", "mean", "point"),
        default="max-abs",
    )
    ap.add_argument("--point-id", type=int)
    ap.add_argument(
        "--sign",
        choices=("same", "flip", "positive-magnitude"),
        required=True,
        help="explicit SU2->PATO heat-flux sign policy",
    )
    ap.add_argument("--patch", default="top")
    ap.add_argument("--initial-temperature", type=float, default=550.0)
    ap.add_argument(
        "--kappa",
        type=float,
        default=1.0,
        help="constant kappa used by this basic PATO BC",
    )
    ap.add_argument("--emissivity", type=float, default=0.0)
    args = ap.parse_args()

    if args.kappa <= 0:
        raise SystemExit("ERROR: --kappa must be positive")

    rows = read_rows(args.csv)
    idx, q_raw = choose(rows, args.selection, args.point_id)
    q_pato = apply_sign(q_raw, args.sign)

    if not math.isfinite(q_pato):
        raise SystemExit("ERROR: selected heat flux is non-finite")

    selected = None if idx is None else rows[idx]

    args.snippet.parent.mkdir(parents=True, exist_ok=True)

    text = f"""// Generated by coupling/SU2_PATO/write_pato_heatflux.py
// Source: {args.csv}
// Selection: {args.selection}
// Sign policy: {args.sign}
// SU2 raw Heat_Flux [W/m^2]: {q_raw:.12e}
// PATO imposed q [W/m^2]: {q_pato:.12e}
//
// Insert this patch dictionary into the PATO temperature field (Ta)
// for the chosen material case. This file is a snippet only.

{args.patch}
{{
    type            basicWallHeatFluxTemperature;
    mode            flux;
    q               uniform {q_pato:.12e};
    kappa           {args.kappa:.12e};
    emissivity      {args.emissivity:.12e};
    value           uniform {args.initial_temperature:.12e};
}}
"""

    args.snippet.write_text(text)

    meta = {
        "source_csv": str(args.csv),
        "selection": args.selection,
        "sign_policy": args.sign,
        "source_point_id": None if selected is None else int(selected["point_id"]),
        "source_xyz": None
        if selected is None
        else [
            float(selected["x"]),
            float(selected["y"]),
            float(selected["z"]),
        ],
        "source_pressure_Pa": None
        if selected is None
        else float(selected["Pressure"]),
        "source_temperature_tr_K": None
        if selected is None
        else float(selected["Temperature_tr"]),
        "source_temperature_ve_K": None
        if selected is None
        else float(selected["Temperature_ve"]),
        "su2_heat_flux_raw_W_m2": q_raw,
        "pato_q_W_m2": q_pato,
        "pato_patch": args.patch,
        "kappa_W_mK": args.kappa,
        "initial_temperature_K": args.initial_temperature,
        "emissivity": args.emissivity,
    }

    meta_path = args.snippet.with_suffix(args.snippet.suffix + ".json")
    meta_path.write_text(json.dumps(meta, indent=2) + "\n")

    print(f"SNIPPET={args.snippet}")
    print(f"METADATA={meta_path}")
    print(f"SELECTION={args.selection}")
    if selected is not None:
        print(f"SOURCE_POINT_ID={selected['point_id']}")
        print(f"SOURCE_XYZ={selected['x']},{selected['y']},{selected['z']}")
        print(f"SOURCE_PRESSURE={selected['Pressure']}")
    print(f"SU2_HEAT_FLUX_RAW={q_raw:.12e}")
    print(f"SIGN_POLICY={args.sign}")
    print(f"PATO_Q={q_pato:.12e}")
    print("PATO_HEATFLUX_SNIPPET=PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
